# Dinamik konfigürasyon dosyası
import:
  types:
    Contact:
      name: "Contact"
      displayName: "Kişi"
      description: "Müşteri ve kullanıcı bilgilerini içe aktarın"
      apiEndpoint: "/api/import/Contact"
      validationEndpoint: "/api/import/Contact/validate"
      enabled: true
      fields:
        - name: "externalId"
          label: "Dış ID"
          type: "string"
          required: false
          description: "Harici sistemdeki benzersiz kimlik"
        - name: "firstName"
          label: "Ad"
          type: "string"
          required: true
          validation:
            minLength: 2
            maxLength: 50
        - name: "lastName"
          label: "Soyad"
          type: "string"
          required: true
          validation:
            minLength: 2
            maxLength: 50
    
    Ticket:
      name: "Ticket"
      displayName: "Bilet"
      description: "Destek biletlerini içe aktarın"
      apiEndpoint: "/api/import/Ticket"
      validationEndpoint: "/api/import/Ticket/validate"
      enabled: true
      fields:
        - name: "title"
          label: "Başlık"
          type: "string"
          required: true
          validation:
            minLength: 5
            maxLength: 200
        - name: "description"
          label: "Açıklama"
          type: "string"
          required: true
          validation:
            minLength: 10

  validation:
    strictMode: false
    maxErrors: 100
    skipInvalidRows: true

  processing:
    batchSize: 1000
    threadPoolSize: 4
    timeoutMs: 30000

# Cache konfigürasyonu
spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=1h

# Async processing
async:
  core-pool-size: 4
  max-pool-size: 8
  queue-capacity: 100
  thread-name-prefix: "import-"
